ifaddr/_posix.py
This is only a workaround. I think this should be fixed on cygwin/newlib side.
=> GH-1 workaround cygwin netmask family bug

ifaddr/_shared.py, setup.py
I ran into this NULL issue on a ubuntu 12 system and after debugging the issue I saw that the server had many interfaces and perhaps one of them was disabled or invalid config and therefore causing get_adapters to panic
after adding the check "ifaddr" is able to list all valid and active adapters
=> issue #8 : check if sockaddr_ptr is NULL

setup.py
`ifaddr` [depends on the `ipaddress` module](https://github.com/pydron/ifaddr/blob/e6163693b6b6d85aad711c3a6849ce7e3bc80d01/setup.py#L39). Before Python 3.3, ipaddress was a separate module, but it’s [now shipped with vanilla Python](https://docs.python.org/3/library/ipaddress.html):
> ### `ipaddress` — IPv4/IPv6 manipulation library
>
> …
>
> *New in version 3.3.*
This means that from Python 3.3 onward, it’s not necessary to add `ipaddress` as an install dependency anymore.
More than that, the explicit dependency is problematic, because users of Python 3.3 and newer will get an error message. The reason is that `ipaddress` won’t be found as a separate module anymore, even though it’s implicitly available.
For instance, running [`python-miio`](https://github.com/rytilahti/python-miio), …
=> Restrict ipaddress dependency to Python < 3.3

ifaddr/_shared.py
This allows the `sockaddr_to_ip` call to work on
OpenBSD.  Before this patch, the call returns "None" and after it
returns the IP addresses associated with the interfaces.
Before the change, unit tests don't pass on OpenBSD, after the change tests pass.
=> Add OpenBSD support to ifaddr

setup.py
A user had reported that the install_requires= line of the setup causes
issues #14. this is due to various setup tools versions supporting varying syntax for the data being passed. 
This update changes it so that the testing of the python version happens in the ifaddr package and not in setuptools. This is a far better way to go about it due to the very large number of setup tools versions  available. of which different versions support different mechanisms of parsing the data in the install_requires parameter, but also install_requires as a parameter might not be supported either.
so the 2 choices would be to check the setup tools version and if it is not up to snuff then throw an error. or simply use a different mechanism like I have to not have to worry about any of the setup tools …
=> Fixes setup.py install_requires line to not be dependant on a setup tools version

ifaddr/_posix.py, ifaddr/_shared.py, ifaddr/_win32.py
Interface index is a relatively rarely used property of an adapter.
However, it is required for cases like joining an IPv6 multicast
group, and is very tricky to get on Windows. This small change makes
working with IPv6 multicast much easier.
=> Expose interface index

ifaddr/_posix.py
As reported in #23 by Jorge Schrauwen on Illumos/Solaris getifaddrs and
freeifaddrs live in libsocket instead of libc, let's handle that.
Closes #23.
=> Fix Illumos/Solaris compatibility

setup.cfg
The project doesn't have any platform-specific native code so we might
as well build wheels that can be used everywhere.
This should allow installing the package on systems that can't install
the source distributions because of outdated setuptools.
=> Build universal wheels for simplicity

README.rst, ifaddr/_posix.py, ifaddr/_win32.py, setup.py
Sometimes it's useful to know the MAC address of an interface
even if it does not have an IP configured
=> Add an option to include ip-less adapters

ifaddr/netifaces.py, ifaddr/test_ifaddr.py, requirements-dev.txt
This is part of netifaces compatibility layer I figured would be helpful
to people trying to avoid installing netifaces while still keeping their
netifaces-using code mostly intact.
=> Implement netifaces.interfaces()

.github/workflows/ci.yml, README.rst, ifaddr/_posix.py, ifaddr/_win32.py, setup.cfg, setup.py
They reached their end of life some time ago and supporting them would
make some upcoming changes more difficult than they should be.
=> Drop Python 2.7 (including PyPy 2) and 3.5 support

.github/workflows/ci.yml
It's annoying when I created a PR from a branch in this repository and
all the builds run twice (once for push, once for pull_request).
=> Don't run CI on non-master branches

ifaddr/_posix.py, ifaddr/_win32.py
The errors:
% mypy ifaddr
ifaddr/_win32.py:89: error: Argument 1 to "IP" has incompatible type "Union[str, Tuple[str, int, int], None]"; expected "Union[str, Tuple[str, int, int]]"
ifaddr/_posix.py:78: error: Unsupported operand types for + ("str" and "None")
ifaddr/_posix.py:78: note: Right operand is of type "Optional[str]"
Found 2 errors in 2 files (checked 6 source files)
In order to avoid using None there let's raise exception if the
preconditions are not met.
=> Fix two type errors detected by Mypy

setup.py
The marker file express the fact the the package contains type hints and
that the type hints should be used by type checkers.
=> Include the py.typed marker in the package

requirements-dev.txt
Make CI green by pinning all development dependencies to versions which have been current at the time of the last release (0.2.0). This gives a starting point to update dev requirements along with the code base.
=> Pin developer package requirements

setup.py
Support for Python 3.7 has officially been removed from the library, hence remove it from the classifiers list.
=> Drop Python 3.7 from classifiers

ifaddr/_shared.py, ifaddr/test_ifaddr.py
- Only do the int conversion once in `ipv6_prefixlength` since the underlying `ipaddress` module will do it every time
- Avoid trying to construct ipv4 addresses when we know its an ipv6 address in `sockaddr_to_ip` since `ip_address` tries ipv4 first, fails, and than tries ipv6
https://github.com/python/cpython/blob/974847be443e9798615e197ec6642e546a71a6b0/Lib/ipaddress.py#L46
On my system which has 28 ipv6 addresses running Python 3.11.5 (main, Aug 24 2023, 15:09:45) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
before
```
Calling get_adapters 10000 took 6.78751229098998 seconds
```
after
```
Calling get_adapters 10000 took 3.899116750084795 seconds
```
```python
from ifaddr import get_adapters
import time
iterations = 10000
start = time.perf_counter()
for _ in range(iterations): …
```
=> Speed up parsing IPv6 addresses

pyproject.toml
Fixup for e389d298536c4d46770cdf044bb08e828afa0da5
=> Fix: drop Python 3.7 support

setup.py
See #55 -- there's no fixing 0.2.0 short of yanking it, but at least the next release will be better.
=> Bring packaging metadata in line with stated supported versions of Python

.github/dependabot.yml
Add depandabot to run once a month to avoid outdated GH actions. Also group all updates to 1 PR.
Fixes #69
=> Add Dependabot for GH actions update

.readthedocs.yaml, pyproject.toml, uv.lock
I want to get the documentation building on RTD.
The YAML configuration is based on the one from the RTD documentation[1] and some dependency-group-related suggestions from [2].
[1] https://docs.readthedocs.com/platform/latest/build-customization.html#install-dependencies-with-uv
[2] https://github.com/readthedocs/readthedocs.org/issues/11766#issuecomment-2590635483
=> Provide an initial ReadTheDocs setup
